server:
  port: 8084

spring:
  application:
    name: contact-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/contact_db}
  
  # Mail Configuration (Example using Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your.email@gmail.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true